name: "Say hi"
on: [push]
jobs:
  say-hi:
    name: "Print hi on log"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi, developer!"
  test-app:
    name: "Test application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install -r ./requirements.txt
      - run: pytest
